SELECT A.*,
        B.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID;


---Mostrar la cantidad de empleados por departamento.
SELECT NVL(B.DEPARTMENT_NAME,'Sin departamento'), COUNT(*) AS CANTIDAD_EMPLEADOS
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
GROUP BY NVL(B.DEPARTMENT_NAME,'Sin departamento');


--Mostrar el salario total por departamento
SELECT B.DEPARTMENT_NAME, SUM(SALARY) AS SALARIO_TOTAL
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
GROUP BY B.DEPARTMENT_NAME;


SELECT * 
from employees 
where first_name like 'Ne%a%';

SELECT B.DEPARTMENT_NAME, ROUND(AVG(SALARY),2) AS SALARIO_PROMEDIO
FROM EMPLOYEES  A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
GROUP BY B.DEPARTMENT_NAME;


SELECT MAX(SALARY)
FROM EMPLOYEES;


SELECT MIN(SALARY)
FROM EMPLOYEES;

SELECT * 
FROM EMPLOYEES 
WHERE SALARY = 2100;




--INFORMACION AGREGADA (AGRUPADA O RESUMIDA)
--INFORMACIÓN SEGREGADA (DETALLE)