SELECT 
    A.employee_id,
    A.first_name,
    A.last_name,
    A.email,
    A.phone_number,
    A.hire_date,
    A.job_id,
    B.JOB_TITLE,
    A.salary,
    A.commission_pct,
    A.manager_id,
    A.department_id,
    C.MANAGER_ID,
    C.FIRST_NAME AS MANAGER_FIST_NAME,
    C.LAST_NAME AS MANAGER_LAST_NAME,
    D.FIRST_NAME AS MANAGER2_FIRST_NAME,
    D.LAST_NAME AS MANAGER2_LAST_NAME,
    E.DEPARTMENT_NAME,
    E.LOCATION_ID,
    F.CITY,
    F.COUNTRY_ID,
    G.COUNTRY_NAME,
    G.REGION_ID,
    H.REGION_NAME
FROM employees A
INNER JOIN JOBS B
ON (A.JOB_ID = B.JOB_ID)
LEFT JOIN EMPLOYEES C
ON (A.MANAGER_ID = C.EMPLOYEE_ID)
LEFT JOIN EMPLOYEES D
ON (C.MANAGER_ID = D.EMPLOYEE_ID)
LEFT JOIN DEPARTMENTS E
ON (A.DEPARTMENT_ID = E.DEPARTMENT_ID)
LEFT JOIN LOCATIONS F
ON (E.LOCATION_ID = F.LOCATION_ID)
LEFT JOIN COUNTRIES G
ON (F.COUNTRY_ID = G.COUNTRY_ID)
LEFT JOIN REGIONS H
ON (G.REGION_ID = H.REGION_ID);


SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM REGIONS;
--wILLIAM 205


SELECT * FROM JOB_HISTORY;


--Consultas equivalentes a inner join
SELECT A.FIRST_NAME, A.LAST_NAME,
        B.DEPARTMENT_NAME
FROM EMPLOYEES A
INNER JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);

SELECT A.FIRST_NAME, A.LAST_NAME,
        B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID = B.DEPARTMENT_ID;


--Consultas equivalentes a leftjoin
SELECT A.FIRST_NAME, A.LAST_NAME,
        B.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);

SELECT A.FIRST_NAME, A.LAST_NAME,
        B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID(+);--Esto es un left join utilizando productos cartesianos




---
SELECT 
    A.employee_id,
    A.first_name,
    A.last_name,
    A.email,
    A.phone_number,
    A.hire_date,
    A.job_id,
    B.JOB_TITLE,
    A.salary,
    A.commission_pct,
    A.manager_id,
    A.department_id,
    C.MANAGER_ID,
    C.FIRST_NAME AS MANAGER_FIST_NAME,
    C.LAST_NAME AS MANAGER_LAST_NAME,
    D.FIRST_NAME AS MANAGER2_FIRST_NAME,
    D.LAST_NAME AS MANAGER2_LAST_NAME,
    E.DEPARTMENT_NAME,
    E.LOCATION_ID,
    F.CITY,
    F.COUNTRY_ID,
    G.COUNTRY_NAME,
    G.REGION_ID,
    H.REGION_NAME
FROM employees A,
        JOBS B,
        EMPLOYEES C,
        EMPLOYEES D,
        DEPARTMENTS E,
        LOCATIONS F,
        COUNTRIES G,
        REGIONS H
WHERE A.JOB_ID = B.JOB_ID
AND   A.MANAGER_ID = C.EMPLOYEE_ID(+)
AND C.MANAGER_ID = D.EMPLOYEE_ID (+)
AND A.DEPARTMENT_ID = E.DEPARTMENT_ID(+)
AND E.LOCATION_ID = F.LOCATION_ID(+)
AND F.COUNTRY_ID = G.COUNTRY_ID(+)
AND G.REGION_ID = H.REGION_ID(+);



